Importing AFNI 0.20070305~dfsg.1 Imported from tarball: AFNI_2006_12_22_0933.tgz Original MD5: 33244de30af7c03896c9c0aab75016dd AFNI claimed to be version: 0.20061222.0933

diff --git a/@Align_Centers b/@Align_Centers
--- a/@Align_Centers
+++ b/@Align_Centers
@@ -64,20 +64,19 @@ PARSE:
       @ cnt ++
    end
    
-SET_PARAMS:
+SET_PARAMS: 
 set v2_vw = `@GetAfniView $v2i`
-set pth2 = $2:h
+set pth2 = $v2i:h
 if ("$pth2" == "$v2i") then 
    set pth2 = .
 endif
 
 set v2_pref = `@GetAfniPrefix $v2i`
 set v2 = $pth2/$v2_pref$v2_vw
-
-
+ 
 CHECKS:
 #make sure output doe not exist
-if ( ! -f $v2.HEAD || (! -f $v2.BRIK && ! -f $v2.BRIK.gz)) then
+if ( ! -f $v2.HEAD || (! -f $v2.BRIK && ! -f $v2.BRIK.gz && ! -f $v2.BRIK.bz2 && ! -f $v2.BRIK.Z)) then
    echo "Error: base brick $v2 not found."
    goto END
 endif
@@ -142,33 +141,36 @@ foreach v1foli ( $v1_list )
    set v1fol_pref = `@GetAfniPrefix $v1foli`
    set v1fol = $v1fol_pth/$v1fol_pref$v1fol_vw
 
+   if ("`@GetAfniID $v1fol`" != "`@GetAfniID $v1i`" && "`@GetAfniID $v1fol`" != "`@GetAfniID $v2i`") then
+      #orientation of v1fol
+      set v1fol_orient = `@GetAfniOrient $v1fol`
+      #change del_RAI to v1fol_orient
+      set del = `@FromRAI -xyz $del_RAI -or $v1fol_orient`
+      echo $del
 
-   #orientation of v1fol
-   set v1fol_orient = `@GetAfniOrient $v1fol`
-   #change del_RAI to v1fol_orient
-   set del = `@FromRAI -xyz $del_RAI -or $v1fol_orient`
-   echo $del
+      #multiply deltas by axis signs
+      set mp = `@AfniOrientSign $v1_orient`
+      set del_refit = ($del)
+      foreach i ( 1 2 3)
+            set del_refit[$i] = `ccalc -form int -expr "$mp[$i] * $del[$i]"`
+      end
 
-   #multiply deltas by axis signs
-   set mp = `@AfniOrientSign $v1_orient`
-   set del_refit = ($del)
-   foreach i ( 1 2 3)
-         set del_refit[$i] = `ccalc -form int -expr "$mp[$i] * $del[$i]"`
-   end
-   
-   #apply the  delta
-   if ($usecp == 1) then
-      if ( `@CheckForAfniDset $v1fol_pth/${v1fol_pref}_shft$v1fol_vw` != 0 ) then
-         echo ""
-         echo "Error `basename $0`"
-         echo "Dset $v1fol_pth/${v1fol_pref}_shft$v1fol_vw found, cleanup first!"
-         echo ""
-         goto END
+      #apply the  delta
+      if ($usecp == 1) then
+         if ( `@CheckForAfniDset $v1fol_pth/${v1fol_pref}_shft$v1fol_vw` != 0 ) then
+            echo ""
+            echo "Error `basename $0`"
+            echo "Dset $v1fol_pth/${v1fol_pref}_shft$v1fol_vw found, cleanup first!"
+            echo ""
+            goto END
+         endif
+         3dcopy $v1fol  $v1fol_pth/${v1fol_pref}_shft
+         3drefit -dxorigin $del_refit[1] -dyorigin $del_refit[2] -dzorigin $del_refit[3] $v1fol_pth/${v1fol_pref}_shft$v1fol_vw
+      else   
+         3drefit -dxorigin $del_refit[1] -dyorigin $del_refit[2] -dzorigin $del_refit[3] $v1fol
       endif
-      3dcopy $v1fol  $v1fol_pth/${v1fol_pref}_shft
-      3drefit -dxorigin $del_refit[1] -dyorigin $del_refit[2] -dzorigin $del_refit[3] $v1fol_pth/${v1fol_pref}_shft$v1fol_vw
-   else   
-      3drefit -dxorigin $del_refit[1] -dyorigin $del_refit[2] -dzorigin $del_refit[3] $v1fol
+   else
+      echo "Child dset $v1fol is same as $v1i or $v2i, skipping it."
    endif
 end   
 
@@ -196,6 +198,11 @@ HELP:
    echo "    you want to eventually align to BASE."
    echo "    Such an operation is needed when DSET and CHILD_'*'"
    echo "    overlap very little, if at all with BASE"
+   echo ""
+   echo " Note that you can specify *.HEAD for the children even "
+   echo " if the wildcard substitution would contain DSET "
+   echo " and possibly even BASE. The script will not process"
+   echo " a dataset twice in one execution."
    echo ""
    echo "   See also @Center_Distance"
    echo ""
