Importing AFNI 0.20091020~dfsg.1 Imported from tarball: AFNI_2008_07_18_1710.tgz Original MD5: 7c47b01721f0484664577911298c67a4 AFNI claimed to be version: 0.20080718.1710

diff --git a/@auto_tlrc b/@auto_tlrc
--- a/@auto_tlrc
+++ b/@auto_tlrc
@@ -1,6 +1,9 @@
 #!/bin/tcsh -f
 
 PARSE: 
+   #exit status
+   set estat = 0
+   
    echo "Parsing ..."
    set Narg = $#
    
@@ -17,7 +20,8 @@ PARSE:
    set KeepTmp = 0
    set verb = 0
    set pd = $pd_default
-   set suf = "_at"
+   #set suf = "_at"
+   set suf = ""
    set rmode = 'default'
    set xform_type = 'affine_general'
    set ss_opt = ''
@@ -26,6 +30,7 @@ PARSE:
    set maxite = ''
    set accept_maxite = 0
    set acpciate = 0
+   set npass = -twopass
    if ("$1" == '') goto HELP
 
    while ($cnt <= $Narg)
@@ -212,6 +217,14 @@ PARSE:
          set accept_maxite = 1
          set donext = 0		
       endif
+      if ($donext && "$argv[$cnt]" == "-onepass") then
+         set npass = ''
+         set donext = 0		
+      endif
+      if ($donext && "$argv[$cnt]" == "-twopass") then
+         set npass = '-twopass'
+         set donext = 0		
+      endif
       if ($donext && "$argv[$cnt]" == "-ncr") then
          set cropt = '';		
          set donext = 0		
@@ -341,11 +354,13 @@ PARSE:
 IN_CHECK:
 if ("$suf" == '' && $KeepView == 1) then
    echo "Cannot use -keep_view and -suffix none"
+   set estat = 1
    goto END
 endif
 
 if ( `@CheckForAfniDset ${ref_in}` != 2 ) then
    echo "Error: Template dset ${ref_in} not found."
+   set estat = 1
    goto END
 endif
 set ttt_pref = "`@GetAfniPrefix ${ref_in}`"
@@ -356,6 +371,7 @@ if ("$ttt_pref" == "TT_avg152EPI") then
    echo "For an equivalent template in MNI space use MNI_EPI+tlrc"
    echo "For an equivalent template in TLRC space use TT_EPI+tlrc"
    echo ""
+   set estat = 1
    goto END
 endif
 
@@ -372,28 +388,33 @@ OK_notice:
 
 if ( `@CheckForAfniDset ${anat_in}` != 2 ) then
    echo "Error: Anatomical dset ${anat_in} not found."
+   set estat = 1
    goto END
 endif 
 
 if ($KeepView == 1) then
    if ( `@CheckForAfniDset ${tt_pref}${anat_view}` != 0 ) then
       echo "Error: Output dset ${tt_pref}${anat_view} exists"
+      set estat = 1
       goto END
    endif
    if ($acpciate == 1) then
       if ( `@CheckForAfniDset ${tt_pref}.Xat.rigid${anat_view}` != 0 ) then
          echo "Error: Output dset ${tt_pref}.Xat.rigid${anat_view} exists"
+         set estat = 1
          goto END
       endif
    endif
 else
    if ( `@CheckForAfniDset ${tt_pref}${ref_view}` != 0 ) then
       echo "Error: Output dset ${tt_pref}${ref_view} exists"
+      set estat = 1
       goto END
    endif
    if ($acpciate == 1) then
       if ( `@CheckForAfniDset ${tt_pref}.Xat.rigid${ref_view}` != 0 ) then
          echo "Error: Output dset ${tt_pref}.Xat.rigid${ref_view} exists"
+         set estat = 1
          goto END
       endif
    endif
@@ -417,6 +438,7 @@ AUTO_TLRC_MODE:
       echo "       Input dataset has $nsb[4] sub-bricks. Use '[]' to "
       echo "       choose one sub-brick."
       echo ""
+      set estat = 1
       goto END
    endif
 
@@ -472,6 +494,7 @@ AUTO_TLRC_MODE:
                      -prefix ${ns_pref} ${ss_opt}
       if ( `@CheckForAfniDset ${ns_pref}${anat_view}` != 2 ) then
          echo "Error: Failed to create skull stripped brain"
+         set estat = 1
          goto END
       endif
    else
@@ -491,6 +514,7 @@ AUTO_TLRC_MODE:
       set ns_pref = ${ns_pref}_clpbel
       if (`@CheckForAfniDset ${ns_pref}${anat_view}` != 2) then 
 			echo "Error: Failed to clip below $clpbelow mm"
+         set estat = 1
          goto END
 		endif
    endif
@@ -518,6 +542,7 @@ AUTO_TLRC_MODE:
                -expr "a*step(b-5000)" -prefix ${tmppref}_resamp
       if ( `@CheckForAfniDset ${tmppref}_resamp${ref_view}` != 2 ) then
          echo "Error: Failed to create resampled volume"
+         set estat = 1
          goto END
       endif
       #clip values to range of input
@@ -534,6 +559,7 @@ AUTO_TLRC_MODE:
       if ( $KeepTmp == 0) rm -f ${tmppref}_resamp* >& /dev/null 
       if ( `@CheckForAfniDset ${rs_pref}${anat_view}` != 2 ) then
          echo "Error: Failed to change view of resampled volume"
+         set estat = 1
          goto END
       endif
    endif
@@ -552,7 +578,7 @@ AUTO_TLRC_MODE:
    set Converged = 0
    while ($Converged == 0 && $pass < 3)
       rm -f ${ns_pref}_WarpDrive.log >& /dev/null
-      3dWarpDrive ${maxite} ${spopt}  -twopass \
+      3dWarpDrive ${maxite} ${spopt}  ${npass} \
                   -${xform_type} -cubic  \
                   -final ${rmode} -1Dmatrix_save ${ns_pref}.Xaff12.1D \
                   -base ${ref_pref_pad}${ref_view} \
@@ -561,10 +587,17 @@ AUTO_TLRC_MODE:
                   -input ${rs_pref}${anat_view}
       if ( `@CheckForAfniDset ${tmppref}_reg_warpdriveout${anat_view}` != 2) then
          echo "Error: Failed in 3dWarpDrive "
+         set estat = 1
          goto END
       endif
       #check for convergence
-      set res = "`cat ${ns_pref}_WarpDrive.log | grep 'RMS\[0\]'`"
+      # this one fails when there is a # in the name! 
+          #set res = "`cat ${ns_pref}_WarpDrive.log | grep 'RMS\[0\]'`"
+      # this should do it:
+         cat "${ns_pref}_WarpDrive.log" > ___cat.tmp
+         set res = "`grep 'RMS\[0\]' ___cat.tmp`"
+         rm -f ___cat.tmp >& /dev/null 
+
       echo "$res"
       set rms_i = `echo "$res" | cut -d ' ' -f3`
       set rms_f = `echo "$res" | cut -d ' ' -f4`
@@ -693,6 +726,7 @@ AUTO_TLRC_MODE:
             -expr "step(a-5000)*b" -prefix ${tt_prefpad}
    if ( `@CheckForAfniDset ${tt_prefpad}${anat_view}` != 2 ) then
       echo "Error: Failed to create tlrced brain"
+      set estat = 1
       goto END
    endif
    
@@ -778,6 +812,7 @@ APAR_MODE:
             -prefix ${tmppref}_warp_tmp -${rmode} ${tmppref}_ipad${anat_view}
    if ( `@CheckForAfniDset ${tmppref}_warp_tmp${anat_view}` != 2) then
       echo "Error: Failed to create tlrced dset"
+      set estat = 1
       goto END
    endif
    
@@ -843,12 +878,14 @@ if ( "$ref_path" == "$ref_in" ) then
    if ( "$ref_path" == '' ) then
       set ref_path = "."
       echo "Error: Template $ref_in could not be located"
+      set estat = 1
       goto END
    endif
    #echo "try finding ref_in in new ref_path"
    if ( `@CheckForAfniDset ${ref_path}/${ref_in}` != 2 ) then
       echo "Error: Template dset ${ref_in} not found"
       echo "   in afni's binaries directory"
+      set estat = 1
       goto END
    endif
    echo "Using template from ${ref_path} ..."
@@ -949,8 +986,11 @@ echo "                       See 3dSkullStrip -help for more details."
 echo "      -ncr           : 3dWarpDrive option -coarserot is now a default."
 echo "                       It will cause no harm, only good shall come of it."
 echo "                       -ncr is there however, should you choose NOT TO"
-echo "                       want coarserot"
-echo "                       used for some reason"
+echo "                       want coarserot used for some reason"
+echo "      -onepass       : Turns off -twopass option for 3dWarpDrive. This will"
+echo "                       speed up the registration but it might fail if the "
+echo "                       datasets are far apart.          "
+echo "      -twopass       : Opposite of -onepass, default."
 echo "      -maxite NITER  : Maximum number of iterations for 3dWarpDrive."
 echo "                       Note that the script will try to increase the "
 echo "                       number of iterations if needed. "
@@ -1023,7 +1063,7 @@ echo "                     Default for 'Usage 1' is quintic"
 echo "                     Default for 'Usage 2' is quintic"
 echo "   -suffix    SUF :  Name the output dataset by append SUF "
 echo "                     to the prefix of the input data for the output."
-echo "                     Default for SUF is _at"
+echo "                     Default for SUF is NONE (see below)"
 echo "              NOTE:  You can now set SUF to 'none' or 'NONE' and enable"
 echo "                     afni's warp on demand features."                
 echo "   -keep_view     :  Do not mark output dataset as +tlrc"
@@ -1133,3 +1173,4 @@ WARN_notice:
    endif
    
 END:
+   exit $estat
