ENH: tune ups for testing (ignore errors for now) + hardening flags

diff --git a/debian/patches/cmake_tests b/debian/patches/cmake_tests
--- a/debian/patches/cmake_tests
+++ b/debian/patches/cmake_tests
@@ -54,27 +54,34 @@
 +ADD_TEST(do.examples ../../tests/xvfb-driver @DO.examples -auto_test)
 --- /dev/null
 +++ b/tests/xvfb-driver
-@@ -0,0 +1,20 @@
-+#!/bin/sh
-+set -eu
+@@ -0,0 +1,27 @@
++#!/bin/bash
++set -u
 +
 +srcdir=$(readlink -f `dirname $0`/..)
-+buildir=$(readlink -f $PWD/..)
++builddir=$(readlink -f $PWD/..)
 +tempdir=`mktemp -d`
 +
 +cleanup() { rm -r "$tempdir"; }
 +trap 'cleanup' EXIT HUP
 +
-+echo "I: buildir=$buildir  srcdir=$srcdir tempdir=$tempdir"
++echo "I: builddir=$builddir  srcdir=$srcdir tempdir=$tempdir"
 +cd $tempdir
-+PATH=$buildir:$buildir/SUMA:$srcdir:$PATH \
++PATH=$builddir:$builddir/SUMA:$srcdir:$PATH \
 +	xvfb-run --auto-servernum --server-num=20 -s "-screen 0 1024x768x24 -ac +extension GLX +render -noreset" \
 +	"$@" 2>&1 | tee __outputlog.txt
++code=${PIPESTATUS[0]}
 +
-+if grep -q Error __*log.txt; then
-+	echo "I: Test failed due to presence of Error messages" >&2
++if [ "$code" != "0" ]; then
++	echo "E: Testing $@ failed. Exit code was $code"
 +	exit 1
 +fi
++
++if grep -q Error __*log.txt; then
++	echo "E: Testing $@ failed due to presence of Error messages" >&2
++	exit 1
++fi
++
 --- a/3DEdge/src/CMakeLists.txt
 +++ b/3DEdge/src/CMakeLists.txt
 @@ -11,3 +11,17 @@ INSTALL(TARGETS 3DEdge
diff --git a/debian/rules b/debian/rules
--- a/debian/rules
+++ b/debian/rules
@@ -8,18 +8,27 @@ upstreamver = $(shell echo $(debver) | cut -d '-' -f 1,1 )
 gitver = $(shell [ -x /usr/bin/git ] && git log -n 1 --oneline $$(git merge-base -a HEAD upstream) | cut -d ' ' -f '4,4')
 
 # Enable hardening on systems which support it
-export DEB_BUILD_HARDENING=1
+# yoh: do not use hardening magic in cc/ld -- leads to spurious
+#      problems if building e.g. via ccache, and logs do not show
+#      then 'effective' set of options used to build any particular
+#      binary
+# export DEB_BUILD_HARDENING=1
+#
+# instead explicitly add those flags if provided
+-include /usr/share/hardening-includes/hardening.make
 
 # get install locations for matlab packages
 include /usr/share/matlab/debian/defs.make
 
 # TODO plugins do not handle this well
 LDFLAGS = $(shell dpkg-buildflags --get LDFLAGS) -Wl,--allow-shlib-undefined
+LDFLAGS+=$(HARDENING_LDFLAGS)
 export LDFLAGS
 
 # need to do it after inclusion of cmake class to get the flag
 # appended after -Wall
 CFLAGS = $(shell dpkg-buildflags --get CFLAGS) -Wno-unused
+CFLAGS+=$(HARDENING_CFLAGS)
 export CFLAGS
 
 # what are we doing this for
@@ -29,6 +38,9 @@ DEB_BUILDDIR = "build-$(DEB_BUILD_GNU_TYPE)"
 # where to build the static corelibs
 DEB_BUILDDIR_STATIC = "build-$(DEB_BUILD_GNU_TYPE)-static"
 
+# Provide details on tests which fail
+export CTEST_OUTPUT_ON_FAILURE=1
+
 DEB_CMAKE_EXTRA_FLAGS = \
     -DAFNI_SHOWOFF:STRING="=Debian-$(DEB_BUILD_GNU_TYPE)" \
     -DBUILD_WITH_INSTALL_RPATH:BOOL=ON \
@@ -37,7 +49,6 @@ DEB_CMAKE_EXTRA_FLAGS = \
     -DCMAKE_EXE_LINKER_FLAGS:STRING="$(LDFLAGS)" \
     -DCMAKE_MODULE_LINKER_FLAGS:STRING="$(LDFLAGS)" \
     -DCMAKE_SHARED_LINKER_FLAGS:STRING="$(LDFLAGS)" \
-    -DCTEST_OUTPUT_ON_FAILURE:BOOL=ON \
     -DAFNI_BUILD_LOCAL_NIFTICLIBS:BOOL=OFF \
     -DAFNI_BUILD_LOCAL_GIFTI:BOOL=OFF \
     -DAFNI_BUILD_LOCAL_3DEDGE3:BOOL=ON \
@@ -57,6 +68,9 @@ DEB_CMAKE_EXTRA_FLAGS = \
 %:
 	dh $@ --buildsystem=cmake
 
+override_dh_auto_test:
+	# for now we ignore failures
+	dh_auto_test || echo "TESTS FAILED"
 
 override_dh_auto_configure:
 	# check whether something changed in the matlab install locations
@@ -71,6 +85,8 @@ override_dh_auto_configure:
       $(DEB_CMAKE_EXTRA_FLAGS) \
       -DBUILD_SHARED_LIBS:BOOL=OFF \
       -DAFNI_BUILD_CORELIBS_ONLY:BOOL=ON
+	# Make xvfb-driver for tests executable since it comes from a patch
+	chmod +x tests/xvfb-driver
 
 
 override_dh_auto_build:
